In [21]:
import torch
import torch.nn as nn
import torch.optim as optim


N = 100000  # number of samples
x = torch.rand(N, 2) * 200 - 100  # numbers in [-100, 100]
y = x.sum(dim=1, keepdim=True)    # y = x1 + x2

print(x)
print(y)


class AddModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)  # input size 2, output size 1

    def forward(self, x):
        return self.linear(x)

model = AddModel()

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.000001) # Reduced learning rate


# Training loop
epochs = 5000

for epoch in range(epochs):
    # Forward pass
    y_pred = model(x)

    # Compute loss
    loss = criterion(y_pred, y)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 50 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.6f}")



tensor([[ 61.7889, -86.3421],
        [-55.4471,  82.9311],
        [ 35.1812,  -4.6791],
        ...,
        [ 12.4992,  84.9237],
        [ 61.7897,  46.5308],
        [ 51.6240,  98.8516]])
tensor([[-24.5532],
        [ 27.4840],
        [ 30.5020],
        ...,
        [ 97.4229],
        [108.3205],
        [150.4756]])
Epoch 50/5000, Loss: 2724.922852
Epoch 100/5000, Loss: 1389.336670
Epoch 150/5000, Loss: 708.381287
Epoch 200/5000, Loss: 361.190918
Epoch 250/5000, Loss: 184.170074
Epoch 300/5000, Loss: 93.912666
Epoch 350/5000, Loss: 47.892555
Epoch 400/5000, Loss: 24.427862
Epoch 450/5000, Loss: 12.463557
Epoch 500/5000, Loss: 6.363077
Epoch 550/5000, Loss: 3.252381
Epoch 600/5000, Loss: 1.666259
Epoch 650/5000, Loss: 0.857500
Epoch 700/5000, Loss: 0.445074
Epoch 750/5000, Loss: 0.234763
Epoch 800/5000, Loss: 0.127534
Epoch 850/5000, Loss: 0.072852
Epoch 900/5000, Loss: 0.044964
Epoch 950/5000, Loss: 0.030744
Epoch 1000/5000, Loss: 0.023489
Epoch 1050/5000, Loss: 0.019790
Epoc

In [22]:
# Inspect learned parameters
weight = model.linear.weight.data
bias = model.linear.bias.data
print("Learned weight:", weight)
print("Learned bias:", bias)



Learned weight: tensor([[1.0000, 1.0000]])
Learned bias: tensor([-0.1253])


In [24]:
# Test the model on some examples
test = torch.tensor([[5.0, 7.0],
                     [-3.0, 10.0],
                     [1000.0, -250.0],
                     [147971,16436931]])

with torch.no_grad():
    preds = model(test)

print("\nTest inputs:")
print(test)
print("Model predictions:")
print(preds)
print("True sums:")
print(test.sum(dim=1, keepdim=True))



Test inputs:
tensor([[ 5.0000e+00,  7.0000e+00],
        [-3.0000e+00,  1.0000e+01],
        [ 1.0000e+03, -2.5000e+02],
        [ 1.4797e+05,  1.6437e+07]])
Model predictions:
tensor([[1.1875e+01],
        [6.8747e+00],
        [7.4987e+02],
        [1.6585e+07]])
True sums:
tensor([[1.2000e+01],
        [7.0000e+00],
        [7.5000e+02],
        [1.6585e+07]])
